[package]
name = "ws"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "*"
env_logger = "*"

serde = { version="*", features=["derive"]}
serde_json = "*"
envy = "*"

openssl = "*"

actix-web = { version="4", features=["openssl"] }
actix-http = "*"

futures = "*"